// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'lib/data/local/assignments.dart';
import 'lib/data/scraped/calendar.dart';
import 'lib/data/scraped/course.dart';
import 'lib/data/scraped/marks.dart';
import 'lib/data/scraped/sem.dart';
import 'lib/data/scraped/timetable.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7844094307121961881),
    name: 'Course',
    lastPropertyId: const obx_int.IdUid(8, 168608596726870728),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8936503331894796738),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 395996700373799160),
        name: 'code',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(1, 369789311095140994),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7508470092222060500),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2245873148290158071),
        name: 'credits',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9089118697839389399),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 7877234235765099062),
        relationField: 'category',
        relationTarget: 'CourseCategory',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9157582254565902923),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 168608596726870728),
        name: 'grade',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'entries',
        srcEntity: 'TimetableEntry',
        srcField: 'course',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2720387347581765818),
    name: 'CourseCategory',
    lastPropertyId: const obx_int.IdUid(4, 6310751137202083207),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 524275998739425411),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6195766448838331458),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6726769845492668866),
        name: 'credits',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6310751137202083207),
        name: 'code',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4060590762657634343),
    name: 'TimetableEntry',
    lastPropertyId: const obx_int.IdUid(9, 694127090680062561),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7708179698590844541),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7544626279304994854),
        name: 'courseId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 4589828323854872255),
        relationField: 'course',
        relationTarget: 'Course',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7505511048872955305),
        name: 'semesterId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 1847986806794642497),
        relationField: 'semester',
        relationTarget: 'Semester',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5304737439253035548),
        name: 'classId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(5, 2171716177972790791),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1012947021753690918),
        name: 'slots',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6559921473306589126),
        name: 'venue',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 245033133731239501),
        name: 'present',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1182395416499823664),
        name: 'absent',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 694127090680062561),
        name: 'grade',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'marks',
        srcEntity: 'Mark',
        srcField: 'entry',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8601934540853103441),
    name: 'Semester',
    lastPropertyId: const obx_int.IdUid(3, 7471720729926564186),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6272342418897829558),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2018849150038441487),
        name: 'code',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(6, 4207088616384992041),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7471720729926564186),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 8359651986574788630),
    name: 'Mark',
    lastPropertyId: const obx_int.IdUid(5, 3778868705849972652),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4036868712142612477),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1348410033699449340),
        name: 'entryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(7, 8093373955574509094),
        relationField: 'entry',
        relationTarget: 'TimetableEntry',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7135166959353976887),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2208526695333411979),
        name: 'score',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3778868705849972652),
        name: 'maxScore',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 1673803474490642497),
    name: 'CalendarEntry',
    lastPropertyId: const obx_int.IdUid(5, 8317470736566838004),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4068744691954281372),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8805042841232445915),
        name: 'semId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(10, 4004628696953133679),
        relationField: 'sem',
        relationTarget: 'Semester',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2504582909949691960),
        name: 'date',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(11, 7314885133191349860),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5926418054102171515),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8317470736566838004),
        name: 'comment',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 7941267040545297008),
    name: 'ExamEntry',
    lastPropertyId: const obx_int.IdUid(9, 4709982309744642399),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4252261356883584139),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 837588652089442888),
        name: 'semId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(12, 3645173848378168003),
        relationField: 'sem',
        relationTarget: 'Semester',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3706808724320620997),
        name: 'course',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3614608383412371584),
        name: 'date',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5442851090369535563),
        name: 'from',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4183329675131114278),
        name: 'to',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6098588498759848749),
        name: 'venue',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7614085969900068546),
        name: 'seatLoc',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4709982309744642399),
        name: 'seatNo',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 655735096497057320),
    name: 'Assignment',
    lastPropertyId: const obx_int.IdUid(8, 1756149690326876027),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 231166197735051193),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8087541202365656930),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6569343766525721464),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8987961969144580934),
        name: 'deadline',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 9099442987843282604),
        name: 'completed',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1756149690326876027),
        name: 'sem',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(9, 655735096497057320),
    lastIndexId: const obx_int.IdUid(13, 1552415668056798070),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [6117339244360381770],
    retiredIndexUids: const [3191994156590455572, 1552415668056798070],
    retiredPropertyUids: const [
      3594803508846366057,
      952155053874008187,
      6862399241802356519,
      8947147389713750571,
      8945857763459413324,
      5791292606650345061,
      3983228616316491681,
      1532407042799090196,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Course: obx_int.EntityDefinition<Course>(
      model: _entities[0],
      toOneRelations: (Course object) => [object.category],
      toManyRelations: (Course object) => {
        obx_int.RelInfo<TimetableEntry>.toOneBacklink(
          2,
          object.id,
          (TimetableEntry srcObject) => srcObject.course,
        ): object.entries,
      },
      getId: (Course object) => object.id,
      setId: (Course object, int id) {
        object.id = id;
      },
      objectToFB: (Course object, fb.Builder fbb) {
        final codeOffset = fbb.writeString(object.code);
        final nameOffset = fbb.writeString(object.name);
        final typeOffset = fbb.writeString(object.type);
        final gradeOffset = object.grade == null
            ? null
            : fbb.writeString(object.grade!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, codeOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addFloat64(3, object.credits);
        fbb.addInt64(4, object.category.targetId);
        fbb.addOffset(5, typeOffset);
        fbb.addOffset(7, gradeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final codeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final creditsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object =
            Course(
                id: idParam,
                code: codeParam,
                name: nameParam,
                type: typeParam,
                credits: creditsParam,
              )
              ..grade = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 18);
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.category.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Course>(
          object.entries,
          store,
          obx_int.RelInfo<TimetableEntry>.toOneBacklink(
            2,
            object.id,
            (TimetableEntry srcObject) => srcObject.course,
          ),
        );
        return object;
      },
    ),
    CourseCategory: obx_int.EntityDefinition<CourseCategory>(
      model: _entities[1],
      toOneRelations: (CourseCategory object) => [],
      toManyRelations: (CourseCategory object) => {},
      getId: (CourseCategory object) => object.id,
      setId: (CourseCategory object, int id) {
        object.id = id;
      },
      objectToFB: (CourseCategory object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final codeOffset = fbb.writeString(object.code);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.credits);
        fbb.addOffset(3, codeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final codeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final creditsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final object = CourseCategory(
          id: idParam,
          code: codeParam,
          name: nameParam,
          credits: creditsParam,
        );

        return object;
      },
    ),
    TimetableEntry: obx_int.EntityDefinition<TimetableEntry>(
      model: _entities[2],
      toOneRelations: (TimetableEntry object) => [
        object.course,
        object.semester,
      ],
      toManyRelations: (TimetableEntry object) => {
        obx_int.RelInfo<Mark>.toOneBacklink(
          2,
          object.id,
          (Mark srcObject) => srcObject.entry,
        ): object.marks,
      },
      getId: (TimetableEntry object) => object.id,
      setId: (TimetableEntry object, int id) {
        object.id = id;
      },
      objectToFB: (TimetableEntry object, fb.Builder fbb) {
        final classIdOffset = fbb.writeString(object.classId);
        final slotsOffset = fbb.writeList(
          object.slots.map(fbb.writeString).toList(growable: false),
        );
        final venueOffset = object.venue == null
            ? null
            : fbb.writeString(object.venue!);
        final presentOffset = fbb.writeList(
          object.present.map(fbb.writeString).toList(growable: false),
        );
        final absentOffset = fbb.writeList(
          object.absent.map(fbb.writeString).toList(growable: false),
        );
        final gradeOffset = object.grade == null
            ? null
            : fbb.writeString(object.grade!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.course.targetId);
        fbb.addInt64(2, object.semester.targetId);
        fbb.addOffset(3, classIdOffset);
        fbb.addOffset(4, slotsOffset);
        fbb.addOffset(5, venueOffset);
        fbb.addOffset(6, presentOffset);
        fbb.addOffset(7, absentOffset);
        fbb.addOffset(8, gradeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final classIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final venueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final gradeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final slotsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 12, []);
        final presentParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 16, []);
        final absentParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 18, []);
        final object = TimetableEntry(
          id: idParam,
          classId: classIdParam,
          venue: venueParam,
          grade: gradeParam,
          slots: slotsParam,
          present: presentParam,
          absent: absentParam,
        );
        object.course.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.course.attach(store);
        object.semester.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.semester.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<TimetableEntry>(
          object.marks,
          store,
          obx_int.RelInfo<Mark>.toOneBacklink(
            2,
            object.id,
            (Mark srcObject) => srcObject.entry,
          ),
        );
        return object;
      },
    ),
    Semester: obx_int.EntityDefinition<Semester>(
      model: _entities[3],
      toOneRelations: (Semester object) => [],
      toManyRelations: (Semester object) => {},
      getId: (Semester object) => object.id,
      setId: (Semester object, int id) {
        object.id = id;
      },
      objectToFB: (Semester object, fb.Builder fbb) {
        final codeOffset = fbb.writeString(object.code);
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, codeOffset);
        fbb.addOffset(2, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final codeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = Semester(id: idParam, code: codeParam, name: nameParam);

        return object;
      },
    ),
    Mark: obx_int.EntityDefinition<Mark>(
      model: _entities[4],
      toOneRelations: (Mark object) => [object.entry],
      toManyRelations: (Mark object) => {},
      getId: (Mark object) => object.id,
      setId: (Mark object, int id) {
        object.id = id;
      },
      objectToFB: (Mark object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.entry.targetId);
        fbb.addOffset(2, titleOffset);
        fbb.addFloat64(3, object.score);
        fbb.addFloat64(4, object.maxScore);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final scoreParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final maxScoreParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final object = Mark(
          id: idParam,
          title: titleParam,
          score: scoreParam,
          maxScore: maxScoreParam,
        );
        object.entry.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.entry.attach(store);
        return object;
      },
    ),
    CalendarEntry: obx_int.EntityDefinition<CalendarEntry>(
      model: _entities[5],
      toOneRelations: (CalendarEntry object) => [object.sem],
      toManyRelations: (CalendarEntry object) => {},
      getId: (CalendarEntry object) => object.id,
      setId: (CalendarEntry object, int id) {
        object.id = id;
      },
      objectToFB: (CalendarEntry object, fb.Builder fbb) {
        final dateOffset = fbb.writeString(object.date);
        final typeOffset = fbb.writeString(object.type);
        final commentOffset = fbb.writeString(object.comment);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.sem.targetId);
        fbb.addOffset(2, dateOffset);
        fbb.addOffset(3, typeOffset);
        fbb.addOffset(4, commentOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final dateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final commentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = CalendarEntry(
          id: idParam,
          date: dateParam,
          type: typeParam,
          comment: commentParam,
        );
        object.sem.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.sem.attach(store);
        return object;
      },
    ),
    ExamEntry: obx_int.EntityDefinition<ExamEntry>(
      model: _entities[6],
      toOneRelations: (ExamEntry object) => [object.sem],
      toManyRelations: (ExamEntry object) => {},
      getId: (ExamEntry object) => object.id,
      setId: (ExamEntry object, int id) {
        object.id = id;
      },
      objectToFB: (ExamEntry object, fb.Builder fbb) {
        final courseOffset = fbb.writeString(object.course);
        final dateOffset = fbb.writeString(object.date);
        final fromOffset = fbb.writeString(object.from);
        final toOffset = fbb.writeString(object.to);
        final venueOffset = fbb.writeString(object.venue);
        final seatLocOffset = fbb.writeString(object.seatLoc);
        final seatNoOffset = fbb.writeString(object.seatNo);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.sem.targetId);
        fbb.addOffset(2, courseOffset);
        fbb.addOffset(3, dateOffset);
        fbb.addOffset(4, fromOffset);
        fbb.addOffset(5, toOffset);
        fbb.addOffset(6, venueOffset);
        fbb.addOffset(7, seatLocOffset);
        fbb.addOffset(8, seatNoOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final courseParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final dateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final fromParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final toParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final venueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final seatLocParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final seatNoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final object = ExamEntry(
          id: idParam,
          course: courseParam,
          date: dateParam,
          from: fromParam,
          to: toParam,
          venue: venueParam,
          seatLoc: seatLocParam,
          seatNo: seatNoParam,
        );
        object.sem.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.sem.attach(store);
        return object;
      },
    ),
    Assignment: obx_int.EntityDefinition<Assignment>(
      model: _entities[7],
      toOneRelations: (Assignment object) => [],
      toManyRelations: (Assignment object) => {},
      getId: (Assignment object) => object.id,
      setId: (Assignment object, int id) {
        object.id = id;
      },
      objectToFB: (Assignment object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = fbb.writeString(object.description);
        final semOffset = fbb.writeString(object.sem);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(3, titleOffset);
        fbb.addOffset(4, descriptionOffset);
        fbb.addInt64(5, object.deadline.millisecondsSinceEpoch);
        fbb.addBool(6, object.completed);
        fbb.addOffset(7, semOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final semParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final deadlineParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final completedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final object = Assignment(
          id: idParam,
          sem: semParam,
          title: titleParam,
          description: descriptionParam,
          deadline: deadlineParam,
          completed: completedParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Course] entity fields to define ObjectBox queries.
class Course_ {
  /// See [Course.id].
  static final id = obx.QueryIntegerProperty<Course>(
    _entities[0].properties[0],
  );

  /// See [Course.code].
  static final code = obx.QueryStringProperty<Course>(
    _entities[0].properties[1],
  );

  /// See [Course.name].
  static final name = obx.QueryStringProperty<Course>(
    _entities[0].properties[2],
  );

  /// See [Course.credits].
  static final credits = obx.QueryDoubleProperty<Course>(
    _entities[0].properties[3],
  );

  /// See [Course.category].
  static final category = obx.QueryRelationToOne<Course, CourseCategory>(
    _entities[0].properties[4],
  );

  /// See [Course.type].
  static final type = obx.QueryStringProperty<Course>(
    _entities[0].properties[5],
  );

  /// See [Course.grade].
  static final grade = obx.QueryStringProperty<Course>(
    _entities[0].properties[6],
  );

  /// see [Course.entries]
  static final entries = obx.QueryBacklinkToMany<TimetableEntry, Course>(
    TimetableEntry_.course,
  );
}

/// [CourseCategory] entity fields to define ObjectBox queries.
class CourseCategory_ {
  /// See [CourseCategory.id].
  static final id = obx.QueryIntegerProperty<CourseCategory>(
    _entities[1].properties[0],
  );

  /// See [CourseCategory.name].
  static final name = obx.QueryStringProperty<CourseCategory>(
    _entities[1].properties[1],
  );

  /// See [CourseCategory.credits].
  static final credits = obx.QueryDoubleProperty<CourseCategory>(
    _entities[1].properties[2],
  );

  /// See [CourseCategory.code].
  static final code = obx.QueryStringProperty<CourseCategory>(
    _entities[1].properties[3],
  );
}

/// [TimetableEntry] entity fields to define ObjectBox queries.
class TimetableEntry_ {
  /// See [TimetableEntry.id].
  static final id = obx.QueryIntegerProperty<TimetableEntry>(
    _entities[2].properties[0],
  );

  /// See [TimetableEntry.course].
  static final course = obx.QueryRelationToOne<TimetableEntry, Course>(
    _entities[2].properties[1],
  );

  /// See [TimetableEntry.semester].
  static final semester = obx.QueryRelationToOne<TimetableEntry, Semester>(
    _entities[2].properties[2],
  );

  /// See [TimetableEntry.classId].
  static final classId = obx.QueryStringProperty<TimetableEntry>(
    _entities[2].properties[3],
  );

  /// See [TimetableEntry.slots].
  static final slots = obx.QueryStringVectorProperty<TimetableEntry>(
    _entities[2].properties[4],
  );

  /// See [TimetableEntry.venue].
  static final venue = obx.QueryStringProperty<TimetableEntry>(
    _entities[2].properties[5],
  );

  /// See [TimetableEntry.present].
  static final present = obx.QueryStringVectorProperty<TimetableEntry>(
    _entities[2].properties[6],
  );

  /// See [TimetableEntry.absent].
  static final absent = obx.QueryStringVectorProperty<TimetableEntry>(
    _entities[2].properties[7],
  );

  /// See [TimetableEntry.grade].
  static final grade = obx.QueryStringProperty<TimetableEntry>(
    _entities[2].properties[8],
  );

  /// see [TimetableEntry.marks]
  static final marks = obx.QueryBacklinkToMany<Mark, TimetableEntry>(
    Mark_.entry,
  );
}

/// [Semester] entity fields to define ObjectBox queries.
class Semester_ {
  /// See [Semester.id].
  static final id = obx.QueryIntegerProperty<Semester>(
    _entities[3].properties[0],
  );

  /// See [Semester.code].
  static final code = obx.QueryStringProperty<Semester>(
    _entities[3].properties[1],
  );

  /// See [Semester.name].
  static final name = obx.QueryStringProperty<Semester>(
    _entities[3].properties[2],
  );
}

/// [Mark] entity fields to define ObjectBox queries.
class Mark_ {
  /// See [Mark.id].
  static final id = obx.QueryIntegerProperty<Mark>(_entities[4].properties[0]);

  /// See [Mark.entry].
  static final entry = obx.QueryRelationToOne<Mark, TimetableEntry>(
    _entities[4].properties[1],
  );

  /// See [Mark.title].
  static final title = obx.QueryStringProperty<Mark>(
    _entities[4].properties[2],
  );

  /// See [Mark.score].
  static final score = obx.QueryDoubleProperty<Mark>(
    _entities[4].properties[3],
  );

  /// See [Mark.maxScore].
  static final maxScore = obx.QueryDoubleProperty<Mark>(
    _entities[4].properties[4],
  );
}

/// [CalendarEntry] entity fields to define ObjectBox queries.
class CalendarEntry_ {
  /// See [CalendarEntry.id].
  static final id = obx.QueryIntegerProperty<CalendarEntry>(
    _entities[5].properties[0],
  );

  /// See [CalendarEntry.sem].
  static final sem = obx.QueryRelationToOne<CalendarEntry, Semester>(
    _entities[5].properties[1],
  );

  /// See [CalendarEntry.date].
  static final date = obx.QueryStringProperty<CalendarEntry>(
    _entities[5].properties[2],
  );

  /// See [CalendarEntry.type].
  static final type = obx.QueryStringProperty<CalendarEntry>(
    _entities[5].properties[3],
  );

  /// See [CalendarEntry.comment].
  static final comment = obx.QueryStringProperty<CalendarEntry>(
    _entities[5].properties[4],
  );
}

/// [ExamEntry] entity fields to define ObjectBox queries.
class ExamEntry_ {
  /// See [ExamEntry.id].
  static final id = obx.QueryIntegerProperty<ExamEntry>(
    _entities[6].properties[0],
  );

  /// See [ExamEntry.sem].
  static final sem = obx.QueryRelationToOne<ExamEntry, Semester>(
    _entities[6].properties[1],
  );

  /// See [ExamEntry.course].
  static final course = obx.QueryStringProperty<ExamEntry>(
    _entities[6].properties[2],
  );

  /// See [ExamEntry.date].
  static final date = obx.QueryStringProperty<ExamEntry>(
    _entities[6].properties[3],
  );

  /// See [ExamEntry.from].
  static final from = obx.QueryStringProperty<ExamEntry>(
    _entities[6].properties[4],
  );

  /// See [ExamEntry.to].
  static final to = obx.QueryStringProperty<ExamEntry>(
    _entities[6].properties[5],
  );

  /// See [ExamEntry.venue].
  static final venue = obx.QueryStringProperty<ExamEntry>(
    _entities[6].properties[6],
  );

  /// See [ExamEntry.seatLoc].
  static final seatLoc = obx.QueryStringProperty<ExamEntry>(
    _entities[6].properties[7],
  );

  /// See [ExamEntry.seatNo].
  static final seatNo = obx.QueryStringProperty<ExamEntry>(
    _entities[6].properties[8],
  );
}

/// [Assignment] entity fields to define ObjectBox queries.
class Assignment_ {
  /// See [Assignment.id].
  static final id = obx.QueryIntegerProperty<Assignment>(
    _entities[7].properties[0],
  );

  /// See [Assignment.title].
  static final title = obx.QueryStringProperty<Assignment>(
    _entities[7].properties[1],
  );

  /// See [Assignment.description].
  static final description = obx.QueryStringProperty<Assignment>(
    _entities[7].properties[2],
  );

  /// See [Assignment.deadline].
  static final deadline = obx.QueryDateProperty<Assignment>(
    _entities[7].properties[3],
  );

  /// See [Assignment.completed].
  static final completed = obx.QueryBooleanProperty<Assignment>(
    _entities[7].properties[4],
  );

  /// See [Assignment.sem].
  static final sem = obx.QueryStringProperty<Assignment>(
    _entities[7].properties[5],
  );
}
