// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'lib/data/course.dart';
import 'lib/data/marks.dart';
import 'lib/data/sem.dart';
import 'lib/data/timetable.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7844094307121961881),
    name: 'Course',
    lastPropertyId: const obx_int.IdUid(6, 9157582254565902923),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8936503331894796738),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 395996700373799160),
        name: 'code',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(1, 369789311095140994),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7508470092222060500),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2245873148290158071),
        name: 'credits',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9089118697839389399),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 7877234235765099062),
        relationField: 'category',
        relationTarget: 'CourseCategory',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9157582254565902923),
        name: 'type',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'entries',
        srcEntity: 'TimetableEntry',
        srcField: 'course',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2720387347581765818),
    name: 'CourseCategory',
    lastPropertyId: const obx_int.IdUid(4, 6310751137202083207),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 524275998739425411),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6195766448838331458),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6726769845492668866),
        name: 'credits',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6310751137202083207),
        name: 'code',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4060590762657634343),
    name: 'TimetableEntry',
    lastPropertyId: const obx_int.IdUid(9, 694127090680062561),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7708179698590844541),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7544626279304994854),
        name: 'courseId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 4589828323854872255),
        relationField: 'course',
        relationTarget: 'Course',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7505511048872955305),
        name: 'semesterId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 1847986806794642497),
        relationField: 'semester',
        relationTarget: 'Semester',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5304737439253035548),
        name: 'classId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(5, 2171716177972790791),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1012947021753690918),
        name: 'slots',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6559921473306589126),
        name: 'venue',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 245033133731239501),
        name: 'present',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1182395416499823664),
        name: 'absent',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 694127090680062561),
        name: 'grade',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8601934540853103441),
    name: 'Semester',
    lastPropertyId: const obx_int.IdUid(3, 7471720729926564186),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6272342418897829558),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2018849150038441487),
        name: 'code',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(6, 4207088616384992041),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7471720729926564186),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 8359651986574788630),
    name: 'Mark',
    lastPropertyId: const obx_int.IdUid(5, 3778868705849972652),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4036868712142612477),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1348410033699449340),
        name: 'entryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(7, 8093373955574509094),
        relationField: 'entry',
        relationTarget: 'TimetableEntry',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7135166959353976887),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2208526695333411979),
        name: 'score',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3778868705849972652),
        name: 'maxScore',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 8359651986574788630),
    lastIndexId: const obx_int.IdUid(7, 8093373955574509094),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Course: obx_int.EntityDefinition<Course>(
      model: _entities[0],
      toOneRelations: (Course object) => [object.category],
      toManyRelations: (Course object) => {
        obx_int.RelInfo<TimetableEntry>.toOneBacklink(
          2,
          object.id,
          (TimetableEntry srcObject) => srcObject.course,
        ): object.entries,
      },
      getId: (Course object) => object.id,
      setId: (Course object, int id) {
        object.id = id;
      },
      objectToFB: (Course object, fb.Builder fbb) {
        final codeOffset = fbb.writeString(object.code);
        final nameOffset = fbb.writeString(object.name);
        final typeOffset = fbb.writeString(object.type);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, codeOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addFloat64(3, object.credits);
        fbb.addInt64(4, object.category.targetId);
        fbb.addOffset(5, typeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final codeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final creditsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = Course(
          id: idParam,
          code: codeParam,
          name: nameParam,
          type: typeParam,
          credits: creditsParam,
        );
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.category.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Course>(
          object.entries,
          store,
          obx_int.RelInfo<TimetableEntry>.toOneBacklink(
            2,
            object.id,
            (TimetableEntry srcObject) => srcObject.course,
          ),
        );
        return object;
      },
    ),
    CourseCategory: obx_int.EntityDefinition<CourseCategory>(
      model: _entities[1],
      toOneRelations: (CourseCategory object) => [],
      toManyRelations: (CourseCategory object) => {},
      getId: (CourseCategory object) => object.id,
      setId: (CourseCategory object, int id) {
        object.id = id;
      },
      objectToFB: (CourseCategory object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final codeOffset = fbb.writeString(object.code);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.credits);
        fbb.addOffset(3, codeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final codeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final creditsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final object = CourseCategory(
          id: idParam,
          code: codeParam,
          name: nameParam,
          credits: creditsParam,
        );

        return object;
      },
    ),
    TimetableEntry: obx_int.EntityDefinition<TimetableEntry>(
      model: _entities[2],
      toOneRelations: (TimetableEntry object) => [
        object.course,
        object.semester,
      ],
      toManyRelations: (TimetableEntry object) => {},
      getId: (TimetableEntry object) => object.id,
      setId: (TimetableEntry object, int id) {
        object.id = id;
      },
      objectToFB: (TimetableEntry object, fb.Builder fbb) {
        final classIdOffset = fbb.writeString(object.classId);
        final slotsOffset = fbb.writeList(
          object.slots.map(fbb.writeString).toList(growable: false),
        );
        final venueOffset = object.venue == null
            ? null
            : fbb.writeString(object.venue!);
        final presentOffset = fbb.writeList(
          object.present.map(fbb.writeString).toList(growable: false),
        );
        final absentOffset = fbb.writeList(
          object.absent.map(fbb.writeString).toList(growable: false),
        );
        final gradeOffset = object.grade == null
            ? null
            : fbb.writeString(object.grade!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.course.targetId);
        fbb.addInt64(2, object.semester.targetId);
        fbb.addOffset(3, classIdOffset);
        fbb.addOffset(4, slotsOffset);
        fbb.addOffset(5, venueOffset);
        fbb.addOffset(6, presentOffset);
        fbb.addOffset(7, absentOffset);
        fbb.addOffset(8, gradeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final classIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final venueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final gradeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final slotsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 12, []);
        final presentParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 16, []);
        final absentParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 18, []);
        final object = TimetableEntry(
          id: idParam,
          classId: classIdParam,
          venue: venueParam,
          grade: gradeParam,
          slots: slotsParam,
          present: presentParam,
          absent: absentParam,
        );
        object.course.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.course.attach(store);
        object.semester.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.semester.attach(store);
        return object;
      },
    ),
    Semester: obx_int.EntityDefinition<Semester>(
      model: _entities[3],
      toOneRelations: (Semester object) => [],
      toManyRelations: (Semester object) => {},
      getId: (Semester object) => object.id,
      setId: (Semester object, int id) {
        object.id = id;
      },
      objectToFB: (Semester object, fb.Builder fbb) {
        final codeOffset = fbb.writeString(object.code);
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, codeOffset);
        fbb.addOffset(2, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final codeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = Semester(id: idParam, code: codeParam, name: nameParam);

        return object;
      },
    ),
    Mark: obx_int.EntityDefinition<Mark>(
      model: _entities[4],
      toOneRelations: (Mark object) => [object.entry],
      toManyRelations: (Mark object) => {},
      getId: (Mark object) => object.id,
      setId: (Mark object, int id) {
        object.id = id;
      },
      objectToFB: (Mark object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.entry.targetId);
        fbb.addOffset(2, titleOffset);
        fbb.addFloat64(3, object.score);
        fbb.addFloat64(4, object.maxScore);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final scoreParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final maxScoreParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final object = Mark(
          id: idParam,
          title: titleParam,
          score: scoreParam,
          maxScore: maxScoreParam,
        );
        object.entry.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.entry.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Course] entity fields to define ObjectBox queries.
class Course_ {
  /// See [Course.id].
  static final id = obx.QueryIntegerProperty<Course>(
    _entities[0].properties[0],
  );

  /// See [Course.code].
  static final code = obx.QueryStringProperty<Course>(
    _entities[0].properties[1],
  );

  /// See [Course.name].
  static final name = obx.QueryStringProperty<Course>(
    _entities[0].properties[2],
  );

  /// See [Course.credits].
  static final credits = obx.QueryDoubleProperty<Course>(
    _entities[0].properties[3],
  );

  /// See [Course.category].
  static final category = obx.QueryRelationToOne<Course, CourseCategory>(
    _entities[0].properties[4],
  );

  /// See [Course.type].
  static final type = obx.QueryStringProperty<Course>(
    _entities[0].properties[5],
  );

  /// see [Course.entries]
  static final entries = obx.QueryBacklinkToMany<TimetableEntry, Course>(
    TimetableEntry_.course,
  );
}

/// [CourseCategory] entity fields to define ObjectBox queries.
class CourseCategory_ {
  /// See [CourseCategory.id].
  static final id = obx.QueryIntegerProperty<CourseCategory>(
    _entities[1].properties[0],
  );

  /// See [CourseCategory.name].
  static final name = obx.QueryStringProperty<CourseCategory>(
    _entities[1].properties[1],
  );

  /// See [CourseCategory.credits].
  static final credits = obx.QueryDoubleProperty<CourseCategory>(
    _entities[1].properties[2],
  );

  /// See [CourseCategory.code].
  static final code = obx.QueryStringProperty<CourseCategory>(
    _entities[1].properties[3],
  );
}

/// [TimetableEntry] entity fields to define ObjectBox queries.
class TimetableEntry_ {
  /// See [TimetableEntry.id].
  static final id = obx.QueryIntegerProperty<TimetableEntry>(
    _entities[2].properties[0],
  );

  /// See [TimetableEntry.course].
  static final course = obx.QueryRelationToOne<TimetableEntry, Course>(
    _entities[2].properties[1],
  );

  /// See [TimetableEntry.semester].
  static final semester = obx.QueryRelationToOne<TimetableEntry, Semester>(
    _entities[2].properties[2],
  );

  /// See [TimetableEntry.classId].
  static final classId = obx.QueryStringProperty<TimetableEntry>(
    _entities[2].properties[3],
  );

  /// See [TimetableEntry.slots].
  static final slots = obx.QueryStringVectorProperty<TimetableEntry>(
    _entities[2].properties[4],
  );

  /// See [TimetableEntry.venue].
  static final venue = obx.QueryStringProperty<TimetableEntry>(
    _entities[2].properties[5],
  );

  /// See [TimetableEntry.present].
  static final present = obx.QueryStringVectorProperty<TimetableEntry>(
    _entities[2].properties[6],
  );

  /// See [TimetableEntry.absent].
  static final absent = obx.QueryStringVectorProperty<TimetableEntry>(
    _entities[2].properties[7],
  );

  /// See [TimetableEntry.grade].
  static final grade = obx.QueryStringProperty<TimetableEntry>(
    _entities[2].properties[8],
  );
}

/// [Semester] entity fields to define ObjectBox queries.
class Semester_ {
  /// See [Semester.id].
  static final id = obx.QueryIntegerProperty<Semester>(
    _entities[3].properties[0],
  );

  /// See [Semester.code].
  static final code = obx.QueryStringProperty<Semester>(
    _entities[3].properties[1],
  );

  /// See [Semester.name].
  static final name = obx.QueryStringProperty<Semester>(
    _entities[3].properties[2],
  );
}

/// [Mark] entity fields to define ObjectBox queries.
class Mark_ {
  /// See [Mark.id].
  static final id = obx.QueryIntegerProperty<Mark>(_entities[4].properties[0]);

  /// See [Mark.entry].
  static final entry = obx.QueryRelationToOne<Mark, TimetableEntry>(
    _entities[4].properties[1],
  );

  /// See [Mark.title].
  static final title = obx.QueryStringProperty<Mark>(
    _entities[4].properties[2],
  );

  /// See [Mark.score].
  static final score = obx.QueryDoubleProperty<Mark>(
    _entities[4].properties[3],
  );

  /// See [Mark.maxScore].
  static final maxScore = obx.QueryDoubleProperty<Mark>(
    _entities[4].properties[4],
  );
}
